
import memories from './memories.json';

export interface Memory {
    id: string;
    timestamp: string;
    title: string;
    type: 'inspiration' | 'log' | 'event';
    priority: 'high' | 'medium' | 'low' | 'max';
    context: string;
}

export const MemoryService = {
    getMemories: async (): Promise<Memory[]> => {
        // Loaded from generated JSON (generated by scripts/sync-memory.js)
        return memories as Memory[];
    }
};
