
import skillsData from './skills.json';

export interface Skill {
    id: string;
    name: string;
    description: string;
    category: string;
    path: string;
    tags?: string[];
}

export const SkillService = {
    getSkills: async (): Promise<Skill[]> => {
        // Loaded from generated JSON (generated by scripts/sync-skills.js)
        return skillsData as Skill[];
    }
};
